version: '3.8'

networks: 
    tig-net:

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "airquality"
            INFLUXDB_ADMIN_USER: "admin"
            INFLUXDB_ADMIN_PASSWORD: "airquality21"
        networks: 
            - tig-net
        volumes:
            - /var/lib/influxdb

    telegraf:
        image: telegraf:1.17-alpine
        container_name: telegraf
        depends_on: 
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "airquality"
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks: 
            - tig-net
        privileged: true

    grafana:
        image: grafana/grafana:7.1.3
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_SECURITY_ALLOW_EMBEDDING: "true"
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
            - /var/lib/grafana
        networks: 
            - tig-net
        restart: always