version: '3.8'

networks: 
    tig-net:

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "airquality"
            INFLUXDB_ADMIN_USER: "admin"
            INFLUXDB_ADMIN_PASSWORD: "airquality21"
        networks: 
            - tig-net
        volumes:
            - ./influxdb:/var/lib/influxdb

    telegraf:
        image: telegraf:1.17-alpine
        depends_on: 
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "airquality"
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks: 
            - tig-net
        privileged: true